/*
[CS] The resource.AddFile fixed borked up the server, so I'm commenting these
out for now...

resource.AddFile("materials/buildingblocks/metal_1.vmt")
resource.AddFile("materials/buildingblocks/metal_1.vtf")
resource.AddFile("materials/buildingblocks/metal_1_0.vmt")
resource.AddFile("materials/buildingblocks/metal_1_0.vtf")
resource.AddFile("materials/buildingblocks/metal_1_1.vmt")
resource.AddFile("materials/buildingblocks/metal_1_1.vtf")
resource.AddFile("materials/buildingblocks/metal_1_2.vmt")
resource.AddFile("materials/buildingblocks/metal_1_2.vtf")
resource.AddFile("materials/buildingblocks/metal_1_3.vmt")
resource.AddFile("materials/buildingblocks/metal_1_3.vtf")
resource.AddFile("materials/buildingblocks/metal_1_4.vmt")
resource.AddFile("materials/buildingblocks/metal_1_4.vtf")

resource.AddFile("materials/buildingblocks/logowhite.vmt")
resource.AddFile("materials/buildingblocks/logowhite.vtf")
resource.AddFile("materials/buildingblocks/logo.vmt")
resource.AddFile("materials/buildingblocks/logo.vtf")

resource.AddFile("materials/weapons/scopes/scope2.vmt") --for scout
resource.AddFile("materials/weapons/scopes/scope2.vtf")

resource.AddFile("materials/models/buildingblocks/metal_logo_1_0.vmt")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_0.vtf")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_1.vmt")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_1.vtf")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_2.vmt")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_2.vtf")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_3.vmt")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_3.vtf")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_4.vmt")
resource.AddFile("materials/models/buildingblocks/metal_logo_1_4.vtf")

resource.AddFile("models/buildingblocks/2d_1_2.dx80.vtx")
resource.AddFile("models/buildingblocks/2d_1_2.dx90.vtx")
resource.AddFile("models/buildingblocks/2d_1_2.mdl")
resource.AddFile("models/buildingblocks/2d_1_2.phy")
resource.AddFile("models/buildingblocks/2d_1_2.sw.vtx")
resource.AddFile("models/buildingblocks/2d_1_2.vvd")
resource.AddFile("models/buildingblocks/2d_1_8.dx80.vtx")
resource.AddFile("models/buildingblocks/2d_1_8.dx90.vtx")
resource.AddFile("models/buildingblocks/2d_1_8.mdl")
resource.AddFile("models/buildingblocks/2d_1_8.phy")
resource.AddFile("models/buildingblocks/2d_1_8.sw.vtx")
resource.AddFile("models/buildingblocks/2d_1_8.vvd")
resource.AddFile("models/buildingblocks/2d_2_3.dx80.vtx")
resource.AddFile("models/buildingblocks/2d_2_3.dx90.vtx")
resource.AddFile("models/buildingblocks/2d_2_3.mdl")
resource.AddFile("models/buildingblocks/2d_2_3.phy")
resource.AddFile("models/buildingblocks/2d_2_3.sw.vtx")
resource.AddFile("models/buildingblocks/2d_2_3.vvd")
resource.AddFile("models/buildingblocks/3d_1_1.dx80.vtx")
resource.AddFile("models/buildingblocks/3d_1_1.dx90.vtx")
resource.AddFile("models/buildingblocks/3d_1_1.mdl")
resource.AddFile("models/buildingblocks/3d_1_1.phy")
resource.AddFile("models/buildingblocks/3d_1_1.sw.vtx")
resource.AddFile("models/buildingblocks/3d_1_1.vvd")
resource.AddFile("models/buildingblocks/3d_1_2.dx80.vtx")
resource.AddFile("models/buildingblocks/3d_1_2.dx90.vtx")
resource.AddFile("models/buildingblocks/3d_1_2.mdl")
resource.AddFile("models/buildingblocks/3d_1_2.phy")
resource.AddFile("models/buildingblocks/3d_1_2.sw.vtx")
resource.AddFile("models/buildingblocks/3d_1_2.vvd")
resource.AddFile("models/buildingblocks/blockspawn_1.dx80.vtx")
resource.AddFile("models/buildingblocks/blockspawn_1.dx90.vtx")
resource.AddFile("models/buildingblocks/blockspawn_1.mdl")
resource.AddFile("models/buildingblocks/blockspawn_1.phy")
resource.AddFile("models/buildingblocks/blockspawn_1.sw.vtx")
resource.AddFile("models/buildingblocks/blockspawn_1.vvd")
resource.AddFile("models/buildingblocks/playerspawn_1.dx80.vtx")
resource.AddFile("models/buildingblocks/playerspawn_1.dx90.vtx")
resource.AddFile("models/buildingblocks/playerspawn_1.mdl")
resource.AddFile("models/buildingblocks/playerspawn_1.phy")
resource.AddFile("models/buildingblocks/playerspawn_1.sw.vtx")
resource.AddFile("models/buildingblocks/playerspawn_1.vvd")
*/
